### PR TITLE
Fix #285 creating type def from a parametrized ClassElement

### LINKED ISSUE #285: Micronaut Sourcegen 1.7.3 broke Micronaut Platform 4.8.1 release
I released 4.8.1 with sourcegen 1.7.3 and it broke starter. 

Moreover, [Micronaut SourceGen 1.7.3 should have been a minor release instead of a patch release as it seems it adds features](https://github.com/micronaut-projects/micronaut-sourcegen/releases/tag/v1.7.3). Please refer to: https://micronaut.io/micronaut-roadmap/.

> A patch GitHub Project – bug fixes / build / documentation/patch dependency updates
 

Steps to reproduce : 

Clone branch [`sourcgen` in `micronaut-starter`](https://github.com/micronaut-projects/micronaut-starter/tree/sourcgen)
```
./gradlew :starter-core:compileJava              
=========================================================
Standardized project names are disabled.
Consider enabling them with
    micronautBuild.useStandardizedProjectNames=true
in settings.gradle.

Then you will need to replace project dependencies from
   project(':foo')
to
   project(':micronaut-foo')
in your build scripts
=========================================================

> Task :starter-core:compileJava
error: cannot access GitHubApiClient$Intercepted
  bad class file: /Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/build/classes/java/main/io/micronaut/starter/client/github/v3/GitHubApiClient$Intercepted.class
    undeclared type variable: E
    Please remove or make sure it appears in the correct subdirectory of the classpath.
/Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/src/main/java/io/micronaut/starter/util/NameUtils.java:720: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    public static boolean isGetter(String name, Class<?>[] args) {
                          ^
Note: /Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/src/main/java/io/micronaut/starter/feature/view/React.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning

> Task :starter-core:compileJava FAILED
[Incubating] Problems report is available at: file:///Users/sdelamo/github/micronaut-projects/micronaut-starter/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':starter-core:compileJava'.
> Compilation failed; see the compiler output below.
  /Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/src/main/java/io/micronaut/starter/util/NameUtils.java:720: warning: [dep-ann] deprecated item is not annotated with @Deprecated
      public static boolean isGetter(String name, Class<?>[] args) {
                            ^
  Note: Some input files use unchecked or unsafe operations.
  error: cannot access GitHubApiClient$Intercepted
    bad class file: /Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/build/classes/java/main/io/micronaut/starter/client/github/v3/GitHubApiClient$Intercepted.class
      undeclared type variable: E
      Please remove or make sure it appears in the correct subdirectory of the classpath.
  Note: Recompile with -Xlint:unchecked for details.
  Note: Recompile with -Xlint:deprecation for details.
  Note: /Users/sdelamo/github/micronaut-projects/micronaut-starter/starter-core/src/main/java/io/micronaut/starter/feature/view/React.java uses or overrides a deprecated API.
  1 error
  1 warning

* Try:
> Check your code and dependencies to fix the compilation error(s)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.11.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4s
11 actionable tasks: 2 executed, 4 from cache, 5 up-to-date
```

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.8.1

### PR DESCRIPTION
**Pull request by andriy-dmytruk**

### CODE REVIEW

File: sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ClassTypeDef.java [hunk 1]
```diff
@@ -460,7 +460,7 @@ static ClassTypeDef of(ClassElement classElement) {
                 new ClassElementType(classElement, classElement.isNullable()),
                 classElement.getTypeArguments().entrySet()
                     .stream()
-                    .<TypeDef>map(e -> TypeDef.variable(e.getKey(), TypeDef.erasure(e.getValue())))
+                    .map(e -> TypeDef.erasure(e.getValue()))
```
Comment (andriy-dmytruk) [inline sourcegen-model/src/main/java/io/micronaut/sourcegen/model/ClassTypeDef.java:463]: @dstepanov Not sure why it was a type variable before, but no of the tests seem to be failing by this fix
